//
// Created by User on 21.10.2019.
//

#include "HelpedClass.h"

class HelpedClass {
//    string[] matrix = "Hello";

    string a = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    string b = "BCDEFGHIJKLMNOPQRSTUVWXYZA";
    string c = "CDEFGHIJKLMNOPQRSTUVWXYZAB";
    string d = "DEFGHIJKLMNOPQRSTUVWXYZABC";
    string e = "EFGHIJKLMNOPQRSTUVWXYZABCD";
    string f = "FGHIJKLMNOPQRSTUVWXYZABCDE";
    string g = "GHIJKLMNOPQRSTUVWXYZABCDEF";
    string h = "HIJKLMNOPQRSTUVWXYZABCDEFG";
    string i = "IJKLMNOPQRSTUVWXYZABCDEFGH";
    string j = "JKLMNOPQRSTUVWXYZABCDEFGHI";
    string k = "KLMNOPQRSTUVWXYZABCDEFGHIJ";
    string l = "LMNOPQRSTUVWXYZABCDEFGHIJK";
    string m = "MNOPQRSTUVWXYZABCDEFGHIJKL";
    string n = "NOPQRSTUVWXYZABCDEFGHIJKLM";
    string o = "OPQRSTUVWXYZABCDEFGHIJKLMN";
    string p = "PQRSTUVWXYZABCDEFGHIJKLMNO";
    string q = "QRSTUVWXYZABCDEFGHIJKLMNOP";
    string r = "RSTUVWXYZABCDEFGHIJKLMNOPQ";
    string s = "STUVWXYZABCDEFGHIJKLMNOPQR";
    string t = "TUVWXYZABCDEFGHIJKLMNOPQRS";
    string u = "UVWXYZABCDEFGHIJKLMNOPQRST";
    string v = "VWXYZABCDEFGHIJKLMNOPQRSTU";
    string w = "WXYZABCDEFGHIJKLMNOPQRSTUV";
    string x = "XYZABCDEFGHIJKLMNOPQRSTUVW";
    string y = "YZABCDEFGHIJKLMNOPQRSTUVWX";
    string z = "ZABCDEFGHIJKLMNOPQRSTUVWXY";




//            BCDEFGHIJKLMNOPQRSTUVWXYZA
//            CDEFGHIJKLMNOPQRSTUVWXYZAB
//            DEFGHIJKLMNOPQRSTUVWXYZABC
//            EFGHIJKLMNOPQRSTUVWXYZABCD
//            FGHIJKLMNOPQRSTUVWXYZABCDE
//            GHIJKLMNOPQRSTUVWXYZABCDEF
//            HIJKLMNOPQRSTUVWXYZABCDEFG
//            IJKLMNOPQRSTUVWXYZABCDEFGH
//            JKLMNOPQRSTUVWXYZABCDEFGHI
//            KLMNOPQRSTUVWXYZABCDEFGHIJ
//            LMNOPQRSTUVWXYZABCDEFGHIJK
//            MNOPQRSTUVWXYZABCDEFGHIJKL
//            NOPQRSTUVWXYZABCDEFGHIJKLM
//            OPQRSTUVWXYZABCDEFGHIJKLMN
//            PQRSTUVWXYZABCDEFGHIJKLMNO
//            QRSTUVWXYZABCDEFGHIJKLMNOP
//            RSTUVWXYZABCDEFGHIJKLMNOPQ
//            STUVWXYZABCDEFGHIJKLMNOPQR
//            TUVWXYZABCDEFGHIJKLMNOPQRS
//            UVWXYZABCDEFGHIJKLMNOPQRST
//            VWXYZABCDEFGHIJKLMNOPQRSTU
//            WXYZABCDEFGHIJKLMNOPQRSTUV
//            XYZABCDEFGHIJKLMNOPQRSTUVW
//            YZABCDEFGHIJKLMNOPQRSTUVWX
//            ZABCDEFGHIJKLMNOPQRSTUVWXY
//
};
