//
// Created by User on 21.10.2019.
//

#ifndef PROGRAMMING3_ASSIGNMENT1_EXERCISE_1_2_HELPEDCLASS_H
#define PROGRAMMING3_ASSIGNMENT1_EXERCISE_1_2_HELPEDCLASS_H


class HelpedClass {

};


#endif //PROGRAMMING3_ASSIGNMENT1_EXERCISE_1_2_HELPEDCLASS_H
